name: ci
on:
  push:
    branches:
      - master
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: go.sum
      - run: go vet ./server/...
      - run: go test -race -v ./server/...
      - run: go build ./server/...

  webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: webapp/.nvmrc
          cache: npm
          cache-dependency-path: webapp/package-lock.json
      - run: npm ci
      - run: npm run check-types
      - run: npm run lint
      - run: npm run test -- --ci
      - run: npm run build
